/* Converts the campus map between the editable .svg form and the
   campus-map.js form the app actually loads.

   The app cannot fetch() the .svg when the pages are opened straight from
   disk (file:// blocks it), and inlining 6 MB into map.html blocks first
   paint. A <script> tag works from file://, over http, and offline, so the
   SVG ships as a JS string instead.

   Build   :  node build-map.js build campus-map.svg
   Extract :  node build-map.js extract campus-map.svg
*/
const fs = require('fs');

const JS_FILE = 'campus-map.js';
const [, , mode, svgPath = 'campus-map.svg'] = process.argv;

// Escape non-ASCII so the generated file is pure ASCII and immune to however
// the browser guesses the charset.
const toAscii = s => s.replace(/[^\x00-\x7F]/g, c =>
    '\\u' + c.charCodeAt(0).toString(16).padStart(4, '0'));

if (mode === 'build') {
    const svg = fs.readFileSync(svgPath, 'utf8').trim();

    // A template literal avoids escaping ~13,700 attribute quotes, but only
    // works if the SVG contains none of its delimiters.
    for (const [name, pattern] of [['backtick', /`/], ['${', /\$\{/], ['backslash', /\\/]]) {
        if (pattern.test(svg)) {
            console.error(`SVG contains ${name}; template literal is unsafe. Use JSON.stringify instead.`);
            process.exit(1);
        }
    }

    fs.writeFileSync(JS_FILE,
        '// GENERATED by build-map.js - edit campus-map.svg and rebuild, not this file.\n' +
        'window.CAMPUS_MAP_SVG = `' + toAscii(svg) + '`;\n');

    console.log(`${svgPath} (${svg.length}) -> ${JS_FILE} (${fs.statSync(JS_FILE).size})`);

} else if (mode === 'extract') {
    const js = fs.readFileSync(JS_FILE, 'utf8');
    const start = js.indexOf('`') + 1;
    const end = js.lastIndexOf('`');
    if (start <= 0 || end <= start) { console.error('Could not find the SVG string.'); process.exit(1); }

    // Turn the \uXXXX escapes back into real characters.
    const svg = js.slice(start, end).replace(/\\u([0-9a-f]{4})/gi,
        (_, hex) => String.fromCharCode(parseInt(hex, 16)));

    fs.writeFileSync(svgPath, svg);
    console.log(`${JS_FILE} -> ${svgPath} (${svg.length} bytes)`);

} else {
    console.error('Usage: node build-map.js <build|extract> [campus-map.svg]');
    process.exit(1);
}
